version: '3'

services:
  next:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/workspace
    working_dir: /workspace
    command: yarn dev